#!/usr/bin/env bash
set -eux

# Install FoundationDB clients & server
yum install -y \
  https://repos.foundationdb.org/fdb/releases/7.1.19/redhat7/foundationdb-clients-7.1.19-1.x86_64.rpm \
  https://repos.foundationdb.org/fdb/releases/7.1.19/redhat7/foundationdb-server-7.1.19-1.x86_64.rpm

# Write cluster file (adjust IPs & token)
cat <<EOF >/etc/foundationdb/fdb.cluster
# cluster file generated by Jepsen
cluster fdb-cluster-00
token 41e9b4b3b9c41c8a2e1a3b2c4d5e6f7
127.0.0.1:4500
127.0.0.1:4501
127.0.0.1:4502
127.0.0.1:4503
127.0.0.1:4504
EOF

systemctl enable foundationdb
systemctl start  foundationdb